# Site settings
title: Doctor's Fab
email: iDoctorsFab@gmail.com
url: https://DoctorsFab.github.io
description: "IoT Medical Devices and Solutions."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Doctor's Fab (Keun Bae Kim)

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url:
  - title: facebook
    url: https://www.facebook.com/profile.php?id=100000614634589
  - title: stack-overflow
    url:
  - title: bitbucket
    url:
  - title: github
    url: https://github.com/DoctorsFab

# Build settings
markdown: kramdown
permalink: pretty
